# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# > # this means to ignore newlines until "baseurl:"

# Site settings
title: Advait Kumar
full_name: Advait Kumar
author: Advait Kumar
email: advaitkumar3107@gmail.com
email2: advaitkumar@iitb.ac.in
description: Sneak peek into the work that I have been involved in over the past 4 years/
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://advaitkumar3107.github.io" # the base hostname & protocol for your site
github_username:  advaitkumar3107
linkedin_username: advait-kumar-3107
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google services
google_analytics: UA-172062065-1

#theme
theme: jekyll-theme-minimal

#allow future dates
future: true
